steps:

- name: 'gcr.io/cloud-builders/docker'
  args: ['pull', 'gcr.io/$PROJECT_ID/test-gcb-trigger',]

- name: 'gcr.io/cloud-builders/docker'
  args: 
  - 'build'
  - '-t'
  - 'gcr.io/$PROJECT_ID/test-gcb-trigger'
  - '--cache-from'
  - 'gcr.io/$PROJECT_ID/test-gcb-trigger'
  - '.'

# The image has been pushed initially from a manually
# created build: `gcloud build submit`
# images: ['gcr.io/$PROJECT_ID/test-gcb-trigger']